format: 1
project:
  name: ActionTree
  version: 0.11.0
  status: beta
  short_descriptions:
    github: "Python library executing long concurrent actions with inter-dependencies"
    pypi: "Executes (long) actions in parallel, respecting dependencies between those actions"
    readme:
      - "*ActionTree* is a Python (2.7 and 3.5+) library to execute (long) actions in parallel, respecting dependencies between those actions."
      - You create a dependency graph of actions to be executed and then call the ``execute`` function on its root.
  has_readme_rst: true
  has_github_pages: true
python:
  versions:
    either:
      - at_least: 2.7
        less_than: 3
      - at_least: 3.5
        less_than: 4
  dependencies:
    test:
      - mock
    optional:
      dependency_graphs:
        - graphviz
      gantt:
        - matplotlib
