language: python
python:
- "2.7"
- "3.5"
- "3.6"
sudo: false
addons:
  apt:
    packages:
    - graphviz
install:
- pip install --upgrade pip setuptools coverage
- pip install --upgrade sphinx coverage
- pip install --upgrade graphviz matplotlib
- if [ "v$TRAVIS_PYTHON_VERSION" == "v2.7" ];
  then
    pip install --upgrade mock;
  fi
script:
- export COVERAGE_FILE=/tmp/.coverage
- '(echo "[run]"; echo "branch = True"; echo "include = $(pwd)/ActionTree/*"; echo "concurrency = multiprocessing"; echo "[report]"; echo "exclude_lines ="; echo "  Not unittested: ...") > /tmp/.coveragerc'
- coverage run --rcfile=/tmp/.coveragerc setup.py test
- coverage combine
- if [ "v$TRAVIS_PYTHON_VERSION" == "v2.7" ];
  then
    python setup.py build_sphinx --builder=doctest;
  fi
after_success:
- pip install --upgrade coveralls
- coveralls --rcfile=/tmp/.coveragerc
deploy:
- provider: pypi
  user: jacquev6
  password:
    secure: d3UoCrv3O53EeMhnhcfplSzc6R3aQqWES7d6gMwfeHlVib+k0GWKCMJqwKhrgMiqWxzW/DhK2t0fckwHgId2Fr6NyUZnIIto8X2wbQtbIIxV033y1DsVJgmEi2UjyJ5E7uI8+cnFLa8p7YgPXNt0cKajxHXSfBJY492nlQL1YRc=
  skip_upload_docs: true
  on:
    tags: true
    repo: jacquev6/ActionTree
    python: 2.7
