name: Continuous Integration
on: push
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v1
      - run: development/tests/run.sh ${{ matrix.python_version }}
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: development/checks/run.sh
