name: Continuous Integration
on: push
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v1
      - run: development/tests/run.sh ${{ matrix.python_version }}
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: development/checks/run.sh
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          development/doc/build.sh
          sudo chown runner:docker -R .
          git checkout -- docs/_images
          git diff --exit-code --stat docs
  demo:
    name: Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          development/demo/run.sh

# @todo Publish tagged versions on PyPI
# @todo Ensure repository settings?
# @todo Ensure file headers have copyright notices?
